@extends('layouts.main')
@section('content')
    <div class="container">
        <h2>Cerita Alberthina Asal NTT Membangun Bisnis Cokelat D'Hokiest</h2>
        <img src="{{ asset('img/umkm5.jpg') }}" class="card-img" alt="...">
        <h4>Alberthina Louisa de Queljoe adalah pemilik brand D’hokiest asal Nusa Tenggara Timur yang didirikannya pada tahun 2019. Mulanya Tien, sapaan akrabnya, membangun bisnis olahan dari bahan cokelat, karena adanya pengaruh dari lingkungan kerja dan lingkungan hidup sehari-harinya.</h4>
        <h3>Nama D'Hokiest</h3>
        <h4>Nama D’hokiest berasal dari kata serapan Bahasa Inggris, the hokiest atau berarti ‘yang paling hoki atau beruntung’. “Ini awalnya dari kata dasarnya hoki, artinya beruntung. Jadi dengan ini kita berharap bahwa usaha kita membawa keberuntungan,” kata Tien kepada Kompas.com saat dihubungi Senin (16/20/2023).Tien berharap, dengan memberikan nama D’hokiest untuk usaha kecilnya, bisa membawa keberuntungan dan membuka lapangan pekerjaan bagi orang-orang yang membutuhkan. Tidak hanya untuk dijadikan tempat bekerja, tetapi juga bisa dijadikan tempat untuk belajar, guna membangun kesejahteraan bersama.</h4>
        <h4>Penggunaan Modal Produksi Tien mengatakan, jika dahulu modal yang dia gunakan untuk memulai bisnis ini berkisar Rp7,5 juta. Modal tersebut didapatkannya dari salah seorang saudara yang mendukung Tien untuk mengembangkan usaha kecilnya. Uang tersebut kemudian digunakan Tien untuk membeli sebuah show case atau lemari pendingin khusus, membeli bahan baku cokelat, juga membeli beberapa alat produksi yang dibutuhkan. “Sebenarnya saya sudah ada kulkas sendiri, tetapi karena ini untuk jualan, sehingga tidak bisa kita jadikan satu antara kebutuhan dapur dan kebutuhan bisnis,” ungkap Tien.</h4>
        <h3>Produk Olahan D'Hokiest</h3>
        <img src="{{ asset('img/coklat1.jpeg') }}" class="card-img" alt="...">
        <h4>Produk yang sejak awal dikeluarkan oleh Tien untuk D’hokiest adalah cokelat batang yang memiliki rasa unik, yakni cokelat rasa kelor. Kelor umumnya hanya dikonsumsi sebagai sayuran atau dijadikan teh, namun Tien mengembangkan inovasi produk kelor ke dalam olahan cokelat batang. Untuk pengolahan produk cokelat kelor ini, mulanya dia dapatkan dari pengalamannya menjadi panitia pelatihan usaha kecil untuk ibu-ibu di Kecamatan Kupang, Nusa Tenggara Timur. Melalui kepanitiaan dalam lembaga sosial Alpha Omega, dia berhasil mempelajari dan memodifikasi produk ini hingga membawa kesuksesan bagi dirinya. Saat ini, ragam produk yang dihasilkan D’hokiest ada beberapa jenis makanan dan minuman, di antaranya adalah cokelat kelor, cokelat hela, cokelat kacang mete, cokelat kacang kenari, cokelat kacang tanah, gula sabu minuman sari kacang hijau, dan daun kelor kering. Inovasi produk D’hokiest berasal dari potensi sumber daya alam yang ada di NTT, khususnya di daerah Kelurahan Tarus, Kecamatan Kupang Tengah, Kabupaten Kupang, Nusa Tenggara Timur. Meski memiliki tantangan untuk bisa mendistribusikan produknya ke luar daerah Nusa Tenggara Timur, malah produk hasil olahan D’hokiest kini sudah tersebar di beberapa toko retail dan salah satunya juga sudah diperjual belikan di salah satu pusat oleh-oleh Kabupaten Manggarai Barat, Labuan Bajo. Bagi Tien, meski bisnis ini masih seumur jagung, dia berharap dengan adanya bisnis D’hokiest bisa semakin memberdayakan perempuan di daerah sekitar Kelurahan Tarus, serta menjadi bisnis yang membawa produk olahan NTT untuk bisa semakin banyak dikenali oleh masyarakat Indonesia.</h4>
        <br>
        <a href="/umkm" class="btn btn-dark">Kembali</a>
    </div>
@endsection