@extends('layouts.main')
@section('content')
    <div class="container">
        <h2>BERMODAL 2,2 JUTA, ILY HANDMADE BANYAK DILIRIK PEMBELI DARI LUAR NEGERI</h2>
        <img src="{{ asset('img/umkm4.jpg') }}" class="card-img" alt="...">
        <h4>Produk kerajinan tangan tidak akan ada habisnya, karena terus menghasilkan produk kreasi yang beragam. Apalagi, perubahan tren pasar semakin cepat dan para crafter semakin bisa memahami tren pasar, sehingga produk kerajinan semakin bagus dan trendy. Seperti produk-produk kerajinan yang dihasilkan, Rini Setyowati sebagai owner Ily Handmade yang dirintis sejak tahun 2016. “Saya membuat produk ini awalnya dilakukan sebagai pengisi waktu luang saat pulang kerja, agar tidak bosan. Saya awalnya menggunakan bahan kain import,” tutur Rini kepada Kompas.com saat dihubungi via Zoom, Sabtu (7/10/2023). Nama Ily Handmade terinspirasi dari qoutes Disney, happily ever after yang berarti bahagia selama-lamanya. Dengan nama ini, saya berahap bisa menciptakan kebahagiaan dan kesenangan untuk orang yang menerima dan menggunakan produk kami.</h4>
        <h3>Putuskan Resign</h3>
        <h4>Sebelumnya, wanita asal Sidoarjo ini merupakan seorang perawat di salah satu rumah sakit yang ada di Surabaya. "Saat saya masih menjadi perawat, saya ditugaskan di kamar operasi dan bekerja dengan sistem on call atau stand by," ujarnya. “Jadi jadwal saya itu harus stand by setiap saat. Seperti kalau jam 2 dini hari terjadi kecelakaan, saya harus ke rumah sakit. Sementara, jarak perjalanan saya mamakan waktu selama 1 jam,” lanjut Rini. Hal itu membuat suami Rini mengkhawatirkan keselamatannya, hingga akhirnya pada tahun 2017, Rini memutuskan resign dan disuruh fokus menekuni hobi dan bisnis kerajinan tangan ini.</h4>
        <h3>Inovasi Produk untuk Menghadapi Pesaing</h3>
        <h4>Tak berselang lama, dunia handmade saat itu menjadi booming, sehingga banyak crafter baru yang bemunculan. Mayoritas dari mereka pun menggunakan bahan yang sama dan memiliki motif yang sama pula. Menurut Rini, produk kerajinan tangan sangat terkenal dengan produk yang eksklusif dan limited. Untuk itu, ia mulai berinovasi, membuat perbedaan dalam produk kerajinannya dengan menggunakan teknik menyulam. Ia mulai mencoba mempelajari dua teknik sulam tangan, yaitu teknik kristik dan embroidery. “Ketika saya mencoba, saya lebih menyukai yang embodery, karena dengan teknik ini kita bisa lebih banyak belajar teknik jahitan,” ucapnya. Saya berusaha mencoba berulang kali sampai akhirnya tercipta sebuah tas sulam. Kemudian, tas sulam tersebut saya posting di Facebook. “Respons konsumen sangat antusias, banyak yang tertarik dan banyak yang order. Selain itu, saya juga mengadakan workshop sulam tangan embroidery,” ucapnya lagi.</h4>
        <h3>Sulitnya mengenalkan Produk ke Masyarakat</h3>
        <h4>Modal yang digunakan oleh Rini pada saat memulai Ily Handmade sebesar Rp 500 ribu dan satu mesin jahit seharga Rp 1,7 juta. “Produk handmade membutuhkan waktu dalam pengerjaannya, satu produk biasanya memakan waktu tiga hingga tujuh hari,” ungkap Rini. Dengan menggunakan modal awal sebesar Rp 500 ribu, Rini dapat mengantongi pendapatan sebesar Rp 3 juta hingga Rp 5 juta dalam sebulan. Meskipun demikian, Rini mengaku merasa kesulitan dalam mengenalkan produk buatannya ke masyarakat Indonesia, karena banyaknya produk impor dan produk KW yang beredar. “Kita juga kesulitan mencari tenaga kerja yang benar-benar menyukai dan ahli di bidang ini. Karena sulam membutuhkan ketelatenan, kesabaran, dan fokus yang tinggi,” lanjutnya.</h4>
        <h3>Sukses Menjual ke Jepang dan Amerika</h3>
        <h4>Produk kerajinan karya Rini, mayoritas dibeli oleh konsumen luar kota seperti Jakarta dan luar negeri, sedangkan di Sidoarjo hanya satu hingga dua orang pembeli. Banyak konsumen luar negeri seperti California, Negara bagian di Amerika Serikat bagian barat dan Negara Jepang yang beberapa kali membeli produknya untuk dihadiahkan kepada teman-teman mereka.“Mereka membeli produk kita melalui postingan instagram kita (@Ily.handmade). Mereka Direct Message (DM) dan melanjutkan transaksi melalui WhatsApp.” Selain itu, Rini juga berusaha menjajakan produknya melalui platform online shop, seperti Shopee, Tokopedia, dan Etsy sebagai upaya untuk menarik konsumen dalam negeri dan luar negeri lebih banyak lagi. Rini berharap semoga produk lokal semakin diminati, diapresiasi, dan dihargai oleh masyarakat Indonesia. Bukan hanya itu, ia juga berahap masyarakat Indonesia merasa lebih bangga memakai produk lokal buatan anak bangsa.</h4>    
        <br>
        <a href="/umkm" class="btn btn-dark">Kembali</a>
    </div>
@endsection