@extends('layouts.main')
@section('content')
    <div class="container">
        <h2>Pecah Rekor, "Marvel's Spider-Man 2" Terjual 2,5 Juta Kopi Sehari</h2>
        <img src="{{ asset('img/spiderman1.jpg') }}" class="card-img" alt="...">
        <h4>- Game Marvel's Spider-Man 2 yang dirilis Jumat lalu (20/10/2023) telah mencatat rekor baru untuk PlayStation Studios. Game eksklusif konsol PlayStation 5 (PS5) ini terjual 2,5 juta kopi dalam hari pertama perilisan, sehingga menjadi game rilisan PS Studios dengan penjualan tercepat. Angka ini sudah menghitung jumlah pemesanan awal (pre-order) Marvel's Spider-Man 2 dan game yang di-bundling dengan konsol PS5. Adapun PlayStation Studios merupakan brand di bawah naungan raksasa game Sony Interactive Entertainment, untuk menandai permainan eksklusif (first-party) bikinan perusahaan itu. Studio dalam brand ini mencakup Insomniac Games, yakni tim di balik seri Marvel's Spider-Man, Naughty Dog selaku pembesut seri The Last of Us, dan masih banyak lagi. pasalnya memang merupakan game yang ditunggu-tunggu. Sebab, kedua prekuelnya, yakni Marvel's Spider-Man dan Marvel's Spider-Man: Miles Morales memiliki kualitas yang tinggi, dan mendapatkan ulasan positif baik dari gamer maupun kritikus. Dengan jumlah penjualan game mencapai 2,5 juta kopi, Spider-Man 2 menundukkan rekor permainan God of War Ragnarok (2022), yang tercatat terjual 5,1 juta kopi dalam pekan peluncurannya. Tidak diumbar angka penjualannya pada hari pertama perilisannya. Sebelum Spider-Man 2 dan God of War Ragnarok, rekor penjualan tercepat sebelumnya dipegang oleh The Last of Us Part 2 (2020), dengan lebih dari 4 juta kopi terjual dalam tiga hari sejak peluncurannya. Ada pula Marvel's Spider-Man (2018) dengan 3,3 juta kopi terjual dalam tiga hari. Melihat respons yang positif ini, PlayStation menyampaikan apresiasinya lewat postingnya di media sosial X (dahulu Twitter). "Terima kasih sudah menjadikan peluncuran (Marvel's Spider-Man 2) sukses besar," tulis perusahaan pada Senin (23/10/2023).</h4>
        <br>
        <h3>Cara klaim karakter Freminet di Genshin Impact</h3>
        <img src="{{ asset('img/spiderman2.png') }}" class="card-img" alt="...">
        <h4>Eric Lempel selaku SVP, Global Marketing, Sales, and Business Operations di Sony Interactive Entertainment juga mengucapkan terima kasih kepada para pemain yang berkontribusi dalam pencapaian rekor baru ini. "Sebagai perwakilan dari Sony Interactive Entertainment, saya ingin mengucapkan terima kasih kepada para pemain," ungkap Lempel. "Kami berharap Anda menikmati pengalaman bermain sebagai Peter dan Miles (dua karakter utama Spider-Man 2), dalam petualangan yang luar biasa ini," imbuhnya.</h4>
        <h3> Bisa Main 2 karakter</h3>
        <h4> Marvel's Spider-Man 2 merupakan permainan Spider-Man besutan Insomniac Games pertama yang hanya bisa dimainkan di konsol PS5. Kedua prekuelnya dapat dimainkan di PS5 dan PlayStation 4 (PS4). Sekuel ini memungkinkan pemain untuk mengontrol atau memainkan dua karakter dari kedua prekuel game tersebut, yakni Peter Parker dari Marvel's Spider-Man (2018) dan Miles Morales dari Marvel's Spider-Man: Miles Morales (2020).Kedua pemuda ini memiliki masalahnya masing-masing, misalnya Peter yang tak bisa melunasi pembayaran rumah bibinya, May. Kemudian, ada Miles yang tak memiliki waktu untuk menulis esai, yang menjadi syarat untuk masuk perguruan tinggi. Pada momen yang semrawut ini, keduanya masih harus melindungi kota New York dari serangan para penjahat baru, termasuk Kraven the Hunter dan Venom. Pemain bakal bermain dengan kedua karakter tadi secara bergantian, sembari menelusuri dan membasmi kejahatan di kota New York. Mekanisme penggantian karakter ini mirip dengan di game Grand Theft Auto 5 (GTA V), sehingga gamer bisa mengganti karakter sesuka hati. Duo Spider-Man ini memiliki misi utama dan misi sampingan yang berbeda, sehingga penggantian bisa dilakukan apabila gamer ingin mendalami cerita karakter tertentu, baik Peter maupun Miles. Selain misi, Peter dan Miles juga memiliki kemampuan (skill) yang berbeda, sebagaimana dikutip KompasTekno dari PlayStation, Selasa (24/10/2023). Misalnya, Peter bisa mengeluarkan tentakel hitam untuk menyerang musuh ketika menggunakan kostum Symbiote Suit. Di sisi lain, Miles memiliki kemampuan Venom Blast, yang menghasilkan gelombang petir biru.</h4>
        <br>
        <a href="/game" class="btn btn-dark">Kembali</a>
    </div>
@endsection