@extends('layouts.main')
@section('content')
    <div class="container">
        <h2>"Minecraft" Jadi Game Terlaris Sepanjang Masa, Terjual 300 Juta Kopi</h2>
        <img src="{{ asset('img/minicraft1.png') }}" class="card-img" alt="...">
        <h4>Game populer buatan Mojang Studios, Minecraft, mencatatkan rekor terbaru. Game simulasi merangkai balok-balok piksel tersebut kini telah terjual sebanyak 300 juta kopi. Dengan pencapaian ini, Minecraft otomatis menjadi game terlaris sepanjang masa setelah Grand Theft Auto V (GTA V) buatan Rockstar Games yang terjual sekitar 185 juta kopi, serta versi modern Tetris buatan Electronic Arts yang terjual sekitar 100 juta kopi.  Tonggak sejarah Minecraft ini diumumkan studio game yang berada di bawah naungan Microsoft tersebut dalam sebuah pengumuman di blog resmi mereka. Pengumuman tersebut juga mencantumkan bahwa usia Minecraft saat ini sudah menginjak 15 tahun. Selain jumlah game terjual, Mojang Studios juga mengumumkan pencapaian lainnya yang sudah dijalani semua pengguna Minecraft sejak perilisan perdananya pada 2009 lalu di PC, sebagaimana dirangkum KompasTekno dari halaman resmi Minecraft, Selasa (17/10/2023). Beberapa di antaranya seperti jumlah senjata pickaxe yang sudah dibuat (15 juta pickaxe), jumlah musuh skeleton yang ditebas (15 juta skeleton), jumlah penemuan diamonds (6,7 juta diamonds), dan masih banyak lagi. </h4>
        <h4>Terkait jumlah terjual ratusan juta kopi tadi, pihak Minecraft tidak merinci platform mana yang berkontribusi banyak terhadap total penjualan game tersebut.  Sebab, Minecraft kini tak hanya tersedia di PC, melainkan juga di berbagai platform mencakup PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, Nintendo Switch, Android, dan iOS. Artinya, ada kemungkinan satu orang pengguna memiliki atau membeli lebih dari satu game Minecraft untuk platform atau konsol berbeda yang mereka miliki, supaya mereka bisa melanjutkan progres bermain mereka di platform manapun.  Namun, pencapaian Minecraft ini dihitung hanya untuk satu judul game saja, bukan merupakan satu seri atau franchise dari suatu game.Apabila dihitung dari segi franchise, Minecraft memang masih kalah jauh dari penjualan berbagai judul game dari Super Mario Series di aneka platform yang kini sudah terjual sekitar 800 juta kopi. Game tersebut juga kalah dari seri Tetris, yang kini hadir dengan berbagai judul di platform berbeda, yang terjual sekitar 520 juta kopi. </h4>
         <br>
        <a href="/game" class="btn btn-dark">Kembali</a>
    </div>
@endsection