@extends('layouts.main')
@section('content')
    <div class="container">
        <h2>Saat Jokowi Sampaikan Terima Kasih untuk Warga dan Pekerja di IKN</h2>
        <img src="{{ asset('img/web2.jpg') }}" class="card-img" alt="...">
        <h4>Presiden Joko Widodo (Jokowi) menyaksikan langsung acara bertajuk "Malam Apresiasi Nusantara" di kawasan Ibu Kota Negara (IKN Nusantara), Kabupaten Penajam Paser Utara, Provinsi Kalimantan Timur, Jumat malam (22/9/2023). Dalam sambutannya, Presiden menyampaikan apresiasinya atas dukungan masyarakat dan para pekerja terhadap pembangunan IKN. "Pertama-tama, saya ingin mengucapkan terima kasih yang sebesar-besarnya kepada seluruh masyarakat di sekitar IKN yang telah memberikan dukungan penuh kepada pembangunan IKN," ujar Jokowi sebagaimana dilansir siaran pers Sekretariat Presiden, Sabtu (23/9/2023)."Juga terima kasih sebesar-besarnya kepada para pekerja yang telah bekerja siang malam untuk segera menyelesaikan mewujudkan ibu kota kita, Nusantara," katanya lagi.Presiden Jokowi lantas menyebut bahwa pembangunan IKN adalah pekerjaan yang sangat besar. Oleh karena itu, ia berharap tahun depan di IKN sudah bisa dilaksanakan Upacara Peringatan Hari Kemerdekaan 17 Agustus. "Doa restu Bapak, Ibu, seluruh masyarakat dan seluruh pekerja, sekali lagi kami ucapkan terima kasih," ujarnya.Dalam kesempatan tersebut, Jokowi juga menerima buku "Indonesia Emas 2045" dari Ketua Kamar Dagang dan Industri (Kadin) Indonesia, Arsjad Rasjid.Presiden mengatakan bahwa buku tersebut akan jadi bahan dalam merencanakan peta jalan menuju Indonesia Emas 2045. "Ini akan kita pakai sebagai bahan dalam merencanakan peta jalan menuju Indonesia Maju 2045. Nanti yang menikmati yang muda-muda ini," katanya. Acara kemudian dilanjutkan dengan penampilan musik dari grup band Gigi. Saat tampil, Gigi berkolaborasi dengan Menteri Pekerjaan Umum dan Perumahan Rakyat (PUPR) Basuki Hadimuljono yang bermain drum untuk membawakan dua lagu, yaitu "Janjiku" dan "Nirwana". Selain Gigi, dalam kesempatan itu tampil juga penyanyi Aurelie Moeremans yang membawakan lagu dangdut "Cikini Gondangdia" dan "No Comment".</h4>
        <br>
        <h3>Makan nasi goreng bersama di IKN</h3>
        <img src="{{ asset('img/nusantara1.jpg') }}" class="card-img" alt="...">
        <h4>Usai menghadiri "Malam Apresiasi Nusantara", Presiden Jokowi kemudian mengajak para pegiat seni makan malam bersama di kawasan IKN. Terlihat Jokowi duduk di tengah-tengah para penggiat seni dan berbincang dengan beberapa di antaranya. Suasana akrab dan hangat pun makin terlihat saat Chef Arnlod mulai mengambil alih dapur dan memasak nasi goreng untuk Jokowi juga para pegiat seni yang mengantre untuk dibuatkan masakannya. “Kalau sudah lihat wok kayak gini panggilan kelihatannya ya, malam-malam, ramai-ramai, kapan lagi sih masakin Pak Jokowi nasi goreng,” kata Chef Arnold sambil memasak.Para pegiat seni dan sejumlah menteri tampak menikmati malam tersebut dengan berbincang dan menyantap makanan yang telah disiapkan.Penyiar radio Ralvi Nasution mengungkapkan bahwa momen makan malam di IKN tersebut merupakan momen yang tidak bisa digambarkan dengan kata-kata dan akan selalu diingat. “Kalau biasa kayak gini makan sama teman-teman ya, ini makan sama Presiden, jadi rasanya sangat indescribable, tidak bisa dituturkan dengan kata-kata lah. Ini suasana yang sangat hangat dan saya akan mengingat momen ini sampai kapan pun,” kata Ralvi. Senada dengan Ralvi, komika Insan Nur Akbar memberikan apresiasi kepada Presiden karena dirinya bisa terlibat dalam momen kebersamaan di IKN. "Ini menjadi suatu kehormatan lah, hari ini senang bisa makan bareng Presiden,” ujar Akbar. Suasana malam itu pun makin hangat saat para pegiat seni hingga Menteri PUPR Basuki Hadimuljono bergantian bernyanyi memeriahkan momen akrab itu.Presiden Jokowi pun tampak bergabung menyaksikan pertunjukan musik tersebut.</h4>
        {{-- <br>
        <h3>Direspons Presiden Joko Widodo</h3>
        <img src="{{ asset('img/tiktok2.jpg') }}" class="card-img" alt="...">
        <h4>Curhatan para pedagang offline di sejumlah daerah akhirnya didengar Presiden Joko Widodo. Jokowi mengakui dampak social e-commerce seperti TikTok Shop membuat penjualan dan produksi UMKM anjlok.Jokowi menilai social e-commerce seharusnya hanya sekadar untuk kegiatan media sosial, bukan berjualan. "Di beberapa pasar sudah mulai anjlok menurun karena serbuan, mestinya ini kan dia itu sosial media, bukan ekonomi media," kata Presiden Jokowi usai meninjau jalan di Kabupaten Penajam Paser Utara, Kalimantan Timur, dikutip dari Antara, Sabtu (23/9/2023). Jokowi menegaskan bahwa pemerintah melalui Kementerian Perdagangan telah menyiapkan aturan untuk mengendalikan niaga elektronik atau e-commerce berbasis media sosial.Regulasi yang sedang dirancang tersebut akan mengatur fungsi aplikasi sebagai media sosial dan platform perdagangan atau media ekonomi. "Masih berada posisi regulasinya di Kementerian Perdagangan. Yang lain-lainnya sudah rampung, tinggal di Kementerian Perdagangan. Kita tunggu," ujar Jokowi.</h4> --}}
        <br>
        <a href="/home" class="btn btn-dark">Kembali</a> 

    </div>
@endsection