@extends('layouts.main')
@section('content')
    <div class="container">
        <h2>PDSI Minta Pemerintah Audit Organisasi Profesi yang Himpun Dana Besar Hasil Pengurusan Izin</h2>
        <img src="{{ asset('img/web5.jpg') }}" class="card-img" alt="...">
        <h4>Perkumpulan Dokter Seluruh Indonesia (PDSI) meminta pemerintah mengaudit seluruh organisasi profesi (OP) yang masih menghimpun dana besar dalam pengurusan surat tanda registrasi (STR) maupun surat izin praktik (SIP). Ketua PDSI Jajang Edi Prayitno mengatakan, permintaan ini seiring dengan laporan yang diterima dari tenaga medis dan tenaga kesehatan (nakes) di daerah yang masih dimintai uang iuran hingga 3,5 tahun saat memperpanjang STR. "Sampai kemarin pun masih ada laporan yang masuk ke kami, dalam pengajuan persyaratan perizinan, masih minta iuran 3,5 tahun, kalau dulu 5 tahun. Iuran lagi, ini apa-apaan saya bilang," kata Jajang dalam rapat dengar pendapat (public hearing) perumusan rancangan peraturan pelaksana (RPP) UU Kesehatan secara daring, Senin (25/9/2023)."Kembali lagi ujung-ujungnya yaitu, saya minta nanti kalau betul-betul ditetapkan peraturan pemerintah ini, saya minta untuk dilakukan audit masalah ini. Karena apapun ini meng-collect partisipasi masyarakat, menghimpun dana-dana masyarakat," imbuh dia. Jajang mengaku heran, pengurusan STR dan SIP di beberapa daerah belum kunjung seragam, setelah UU Kesehatan Nomor 17 Tahun 2023 tentang Kesehatan telah diundangkan pada 8 Agustus 2023. Diketahui dalam UU Kesehatan, STR berlaku seumur hidup, sedangkan SIP perlu diperpanjang setiap 5 tahun sekali. "Oleh karena itu, pada kesempatan ini saya usulkan nanti ada pemeriksaan audit untuk organisasi profesi. Semua organisasi termasuk kami, silakan diaudit yang menghimpun dana-dana masyarakat. Saya minta semua untuk diaudit," tutur Jajang.
        <br>
        <h4>Lebih lanjut ia menilai, seharusnya, pengurusan STR dan SIP tidak lagi dipersulit dengan persyaratan yang sama, usai rencana pemerintah menyederhanakan pengurusannya lewat UU baru. Terlebih, dalam UU, rekomendasi organisasi profesi telah dihapus dalam perpanjangan SIP. Tercatat, hanya ada dua syarat mendapatkan SIP, yaitu memiliki Surat Tanda Registrasi (STR) dan tempat praktik. "Enggak perlu dipersoalkan harus ada persyaratan macam-macam, kecuali untuk nakes WNA dan lain-lain, itu memang betul. Atau dokter yang masih praktik, itu perlu persyaratan. Tapi bagi yang sudah enggak praktik lagi, sudah lansia, kenapa harus harus ada persyaratan macam-macam?" tutur Jajang. Menanggapi hal itu, Sekretaris Konsil Tenaga Kesehatan Indonesia, Dion menyebut, usulan-usulan tersebut akan ditampung terlebih dahulu.erkait kesederhanaan mengurus izin, ia memastikan Kementerian Kesehatan (Kemenkes) tidak akan mengabaikan kompetensi tenaga medis maupun tenaga kesehatan. Kesederhanaan kata dia, bukan berarti membuat tenaga medis dan nakes menjadi tidak berkompetensi dan tidak profesional. Oleh karena itu, pengumpulan satuan kredit profesi (SKP) yang digunakan untuk mengurus perpanjangan atau penerbitan STR dan SIP akan melibatkan para ahli di bidangnya. "Beberapa kali dari Ditjen Nakes sudah melakukan koordinasi. Mudah-mudahan (kompetensi) ini juga terjaga, jadi kita tetap mengutamakan keselamatan pasien. Jadi saran-sarannya, jadi catatan buat kami," jelas Dion.</h4>
        </h4>
        <br>
        <a href="/home" class="btn btn-dark">Kembali</a>
    </div>
@endsection