@extends('layouts.main')
@section('content')
    <div class="container">
        <h2>Efisiensi, Satelit HBS Bakti Dibatalkan</h2>
        <img src="{{ asset('img/satelit1.jpeg') }}" class="card-img" alt="...">
        <h4>SATGAS Bakti (Badan Aksesibilitas Telekomunikasi Indonesia) mengakhiri kontrak pengadaan satelit penunjang (HBS – hot backup satellite) yang sedianya untuk cadangan satelit Satria-1 yang sudah berhasil diluncurkan Juni lalu dan akan dioperasikan pada awal 2024. HBS yang dibangun Boeing AS sedianya meluncur Oktober ini, disiapkan untuk menjadi pengganti jika Satria-1 gagal mengorbit. 
            Kedua satelit canggih, multifungsi berteknologi HTS (high throughput satellite), satelit berkapasitas besar yang jejaknya (footprint-nya) bukan cakupan luasnya melainkan titik-titik (spot) tertentu. Kapasitas satelit HTS mencapai 2 kali sampai 100 kali kapasitas satelit konvensional (FSS - fixed satellite service) dengan biaya per bit jauh lebih murah.Satria-1 saat ini sedang menuju orbitnya di 146º bujur timur pada ketinggian 36.000 km di atas Papua. Harga satelitnya 450 juta dollar AS (waktu itu sekitar Rp 6,7 triliun) dibiayai konsorsium yang akan dicicil Bakti selama 15 tahun. Sementara HBS dibiayai Bakti dari dana USO (universal service obligation) yang didapat dari pengumpulan 1,25 persen pendapatan kotor operator seluler, dan hanya disewa kapasitasnya saja dari KNJ (Konsorsium Nusantara Jaya). Satria-1 yang diluncurkan dari Cape Kennedy, Florida, AS, pada 18 Juni 2023 dibangun Thales Alenia Space, kapasitasnya sama dengan HBS, sebesar 150 GB dengan kemampuan menjangkau 150.000 titik tertentu di bumi. 
            Jumlah titik untuk Satria-1 diralat menjadi hanya 50.000 agar kapasitas pada masing-masing titik dapat lebih besar, naik dari perkiraan 1Mbps/titik menjadi 4 Mbps.Masyarakat di tiap titik bisa mengakses transmisi data dari satelit dengan bantuan VSAT (very small aperture terminal), tidak langsung dari satelit. Untuk itu sudah dibangun 11 tempat sebagai stasiun bumi dengan pusat di Cikarang, Jawa Barat. Pembatalan kerja sama membuat Bakti meminta kembali uang sewa yang sudah dibayarkan sebesar Rp 3,5 triliun plus biaya uang (cost of money) yang muncul sejak dibayarkan ke KNJ. Alasan pembatalan, menurut Ketua Satgas Bakti Kominfo, Sarwoto Atmosutarno, Bakti harus fokus pada satelit Satria-1 yang saat beroperasi. Hal itu akan banyak menyita energi dan tidak boleh gagal, baik untuk kapasitas segmen langitnya maupun segmen daratnya. Banyak kalangan memperkirakan, pembatalan kerja sama juga jadi antisipasi datangnya layanan satelit Starlink milik Elon Musk tahun depan yang sudah dapat izin labuh, bekerja sama dengan Telkomsat.Walau berbiaya lebih mahal, mutu layanan Starlink dengan ribuan satelit LEO (low earth orbit – satelit orbit rendah) diyakini lebih baik dibanding layanan satelit GEO (geostationer earth orbit), antara lain karena latensinya (jeda) sangat rendah.</h4>
        <br>
        <h3>Lewat  backhaul</h3>
        {{-- <img src="{{ asset('img/tiktok1.jpg') }}" class="card-img" alt="..."> --}}
        <h4>Ancaman bukan hanya terhadap keberadaaan HBS, tetapi juga satelit Satria-1 dan Satria-Satria berikut yang rencananya akan diluncurkan demi perluasan layanan daerah 3T (tertinggal, terdepan dan terluar). Ada beberapa keunggulan satelit LEO yang tidak mungkin tertandingi satelit GEO, antara lain kapasitasnya yang besar sampai 500 GB. Latensi layanan satelit GEO sekitar 500 milidetik satelit LEO yang orbitnya di ketinggian 500 km hingga 2.000 km di atas bumi, hanya 25 milidetik. Layanan LEO lebih mahal karena usianya hanya 5 tahun dan untuk mencakup seluruh muka bumi perlu dioperasikan 48 satelit, sementara satelit GEO beroperasi sendiri, usianya bisa 15 tahun. Untuk mengakses layanan Starlink, calon pelanggan harus membayar biaya awal 0,9 dollar AS, sekitar Rp 1,4 juta dengan biaya bulanan Rp 2 juta hingga Rp 3 juta.Posisi satelit sering bergeser akibat pengaruh cuaca atau daya tarik bumi dan untuk mengembalikannya, satelit didorong kembali dengan menyalakan roket yang dibawanya. Bahan bakar roket ini menentukan usia satelit yang makin cepat habis jika posisi satelit sering dikoreksi sampai tak terjangkau kendali stasiun bumi. Karena posisinya yang lebih rendah sehingga gaya tarik bumi lebih kuat, satelit LEO harus bergerak terus memutari bumi dengan kecepatan 30.000 km per jam dan kembali ke titik semula setiap 90 menit. Harga tiap satelit LEO milik Elon Musk sekitar 25 juta dollar AS atau hampir Rp 400 miliar. Satelit LEO, Starlink atau ATS, OneWeb, GlobarStar, Lynx dan lainnya, juga Satria-1 yang GEO tidak bisa langsung berkomunikasi dengan ponsel 5G milik pelanggan di bumi.Komunikasi harus melewati backhaul, pengalur jaringan, teknologi yang menghubungkan jaringan tulang punggung ke jaringan akses. Kalaupun langsung dari satelit ke ponsel, menurut pakar satelit Kanaka Hidayat, satelit harus dibuat dengan antena yang sangat besar agar peka terhadap pancaran sinyal ponsel yang kecil. Kabar terbaru di media sosial, ponsel 5G Huawei Mate 60 Pro atau iPhone 15 dikatakan bisa berkomunikasi suara dan data langsung dengan satelit. Jika pun bisa berkomunikasi langsung antara satelit LEO dan ponsel di bumi, hanya ponsel 5G yang dapat melakukannya. Ini karena satelit LEO menggunakan frekuensi unggah dan unduh pada rentang spektrum 12 GHz dan 32 GHz, yang termasuk milimeterband, spektrum yang wajib digunakan untuk layanan 5G.</h4>
        <br>
        <a href="/internet" class="btn btn-dark">Kembali</a> 
    </div>
@endsection