@extends('layouts.main')
@section('content')
    <div class="container">
        <h2>Pemerintah RI Larang Transaksi di TikTok, Hanya Boleh Promosi Hal itu diungkapkan oleh Menteri Perdagangan Zulkifli Hasan </h2>
        <img src="{{ asset('img/transaksi1.jpg') }}" class="card-img" alt="...">
        <h4>Pemerintah melarang social e-commerce bertransaksi langsung di platform media sosial seperti TikTok Shop. Keputusan tersebut diambil dalam rapat terbatas yang dipimpin Presiden Joko Widodo di Istana Kepresidenan, Jakarta, Senin (25/9/2023). "Social e-commerce itu hanya boleh memfasilitasi promosi barang/jasa, tidak boleh transaksi langsung, bayar langsung, enggak boleh lagi," ujar Menteri Perdagangan (Mendag) Zulkifli Hasan usai rapat. Alasan pelarangan ini lantaran social e-commerce hanya diperbolehkan untuk mempromosikan layaknya sebuah iklan, bukan untuk berjualan."Dia hanya boleh promosi, seperti TV ya, iklan boleh, tapi enggak bisa jualan, enggak bisa terima uang, jadi dia semacam platform digital. Tugasnya mempromosikan," katanya. Adapun kesepakatan pelarangan ini diambil supaya tidak seluruh algoritma dikuasai oleh social e-commerce. Selain itu, langlah ini diambil sebagai upaya pemerintah untuk mencegah penyalahgunaan data pribadi dalam kepentingan bisnis.Zulkifli menegaskan, kesepakatan itu akan tertera dalam aturan baru yang merevisi Peraturan Menteri Perdagangan (Permendag) Nomor 50 Tahun 2020. Dia menyebut revisi Permendag itu segera diteken. Dengan demikian, apabila ada social e-commerce yang melanggar maka akan ada peringatan dari Kementerian Komunikasi dan Informatika. "Habis diperingatkan, kemudian ditutup," tegas Zulkifli. Sebelumnya, Jokowi mengakui omzet perdagangan di pasar menurun drastis akibat terdampak perdagangan berbasis elektronik melalui media sosial atau social e-commerce. Hal tersebut disampaikan Presiden saat menjawab pertanyaan wartawan soal tindak lanjut dari banyaknya keluhan pedagang soal TikTok Shop. Menurut Jokowi, omzet penjualan pedagang di sejumlah pasar menjadi anjlok karena perdagangan berbasis online."Karena kita tahu itu berefek pada UMKM, kepada produksi di usaha kecil, usaha mikro, dan juga pada pasar. Ada pasar, di beberapa pasar mulai anjlok menurun karena serbuan," ujar Jokowi di kawasan Ibu Kota Nusantara (IKN) Kalimantan Timur, sebagaimana dilansir siaran pers Sekretariat Presiden, Sabtu (23/9/2023).Dia menegaskan bahwa aturan untuk mengendalikan perdagangan elektronik berbasis media sosial segera disiapkan oleh kementerian terkait. Regulasi itu nantinya mengatur antara media sosial dan platform perdagangan atau ekonomi. Jokowi berjanji aturan yang dimaksud segera tuntas. "Ini baru disiapkan (aturannya), itu kan lintas kementerian dan ini memang baru difinalisasi di Kementerian Perdagangan (Kemendag)," katanya. "Mestinya dia itu sosial media bukan ekonomi media, itu yang baru akan diselesaikan untuk segera diatur," pungkasnya.</h4>
        <br>
        
        <a href="/home" class="btn btn-dark">Kembali</a>
    </div>
@endsection